# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Publish Artifact

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Add PROJECT_VERSION env property with commit short sha
        run: echo "PROJECT_VERSION=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      - name: Set up Java 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: jerry-${PROJECT_VERSION}
          path: build/libs/jerry-$PROJECT_VERSION-rel.jar
      - name: Create Release
        if: github.ref == 'refs/heads/master'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: jerry-$PROJECT_VERSION
          release_name: Jerry $PROJECT_VERSION
          draft: false
          prerelease: true
      - name: Upload release
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/libs/jerry-$PROJECT_VERSION-rel.jar
          asset_name: jerry-$PROJECT_VERSION.jar
          asset_content_type: application/java-archive